project: 
  type: website
  output-dir: docs
toc: true
number-sections: false

format:
  html:
    theme: default
    css: styles.css

website: 
  # repo-url: https://github.com/ss4ws/b23
  title: "Ã€ Vos Plumes!"
  sidebar:
    background: "#fff"
    foreground: "#333"
    style: "docked"
    search: true
    contents:
      - understand-grammar.qmd
      - students.qmd
      - resources.qmd
      # - teachers.qmd
      - about.qmd
  